import { Tenant } from '../models/tenant.model';

export const Tenants: Array<Tenant> = [
  {
    id: '1233',
    name: 'Sarah W',
    email: 'sarah@sarah.com',
    phone_number: '443-098-9043',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1233,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1233,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1234',
    name: 'Daniel K',
    email: 'daniel@daniel.com',
    phone_number: '123-567-9023',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1234,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1234,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1235',
    name: 'Adam N',
    email: 'adam@adam.com',
    phone_number: '187-896-7854',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1235,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1235,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1236',
    name: 'Ronald A',
    email: 'ronald@ronald.com',
    phone_number: '457-781-9871',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1236,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1236,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1237',
    name: 'Genesis U',
    email: 'genesis@genesis',
    phone_number: '564-327-8906',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1237,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1237,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1238',
    name: 'Rodrigo S',
    email: 'rod@rod.com',
    phone_number: '125-672-9023',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1238,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1238,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1239',
    name: 'Mr Nick',
    email: 'nick@nick.com',
    phone_number: '765-092-8971',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1239,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1239,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
  {
    id: '1240',
    name: 'Shawn O',
    email: 'shawn@shawn.com',
    phone_number: '672-098-7123',
    notes: 'This is a test.',
    invoices: [
      {
        id: '1',
        tenant: 1240,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web Development',
        value: 4500,
        additional_notes: 'Adding the 3 new pages.',
      },
      {
        id: '2',
        tenant: 1240,
        created_date: new Date(),
        due_date: new Date(),
        service: 'Web App Fixes',
        value: 2500,
        additional_notes: 'Fixing the bug that caused a $55000 drop in profit.',
      },
    ],
  },
];
